import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 320, height: 900 });
await page.goto('http://localhost:8080', { waitUntil: 'networkidle' });
await page.click('#btn-start');
await page.waitForSelector('#input-team-name');
const html = await page.locator('.parchment-content').innerHTML();
console.log('parchment-content innerHTML:', html.substring(0, 3000));
await browser.close();
