import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 320, height: 900 });
await page.goto('http://localhost:8080', { waitUntil: 'networkidle' });
await page.click('#btn-start');
await page.waitForSelector('#input-team-name');
const p = await page.locator('.parchment-content').boundingBox();
const inp = await page.locator('#input-team-name').boundingBox();
const btn = await page.locator('#btn-confirm-team').boundingBox();
console.log('parchment:', JSON.stringify(p));
console.log('input:', JSON.stringify(inp));
console.log('confirm:', JSON.stringify(btn));
const html = await page.locator('.parchment-content').innerHTML();
console.log('parchment-content innerHTML:', html.substring(0, 2000));
await browser.close();
